version: '2'
services:
  clickhouse.base:
    image: yandex/clickhouse-server:latest
    volumes:
    - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
    - /var/log/clickhouse-server
    environment:
      CLICKHOUSE_SHARD: 1
      CLICKHOUSE_REPLICA: clickhouse.base
      CLICKHOUSE_CONFIG: /etc/clickhouse-server/config.xml
    entrypoint: sh -c 'echo "<?xml version=\"1.0\"?><yandex><macros><shard>$$CLICKHOUSE_SHARD</shard><replica>$$CLICKHOUSE_REPLICA</replica></macros></yandex>" > /etc/clickhouse-server/config.d/macros.xml && /entrypoint.sh'
