FROM golang:alpine
MAINTAINER Eugene Klimov <bloodjazman@gmail.com>

RUN apk --no-cache add git && \
    mkdir -p /zetcd && \
    GOPATH=/zetcd go get github.com/coreos/zetcd/cmd/zetcd && \
    apk del git && \
    cp -v /zetcd/bin/zetcd /bin/zetcd && \
    rm -rf /zetcd

ENV ETCD_HOST=etcd:2379

ENTRYPOINT zetcd --zkaddr 0.0.0.0:2181 --endpoints ${ETCD_HOST}